### ISSUE TITLE
Dark Theme Affects QR Code

### ISSUE THREAD

**Issue by zetaomegagon** [hacker1024/android-wifi-qr-code-generator#4]
When changed to dark theme three things have happened:

- QR code is color inverted
- QR code and background are similar shade of grey
- Restart required (sometimes) for theme change to take full effect (QR code)

In each case the QR code is not useable.

LG G5 H830, Nougat 7.1.2, LineageOS for MicroG

**Comment by hacker1024** [comment]
The colour inversion is deliberate. It works with all the scanners I've tested. Can you try another scanner?
