### ISSUE TITLE
No longer works with Android Pie

### ISSUE THREAD

**Issue by rjamorim** [hacker1024/android-wifi-qr-code-generator#5]
Android Pie changed the format of the wifi configuration storage to a XML file (WifiConfigStore.xml)

Sure enough that change broke the QR Code Generator. Any plans to adapt the app to use the new file format?

**Comment by hacker1024** [comment]
Since this feature is going to be built in to Android Q, I don't really plan on fixing it again. If enough people are stuck on Pie and need this, then perhaps, but I think the majority of this app's users have phones that can be upgraded with custom ROMs.
